/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.cm.model.impl;

import com.liferay.cm.model.Term;
import com.liferay.cm.model.TermModel;
import com.liferay.cm.model.TermSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Term service. Represents a row in the &quot;CM_Term&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TermModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TermModelImpl extends BaseModelImpl<Term> implements TermModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a term model instance should use the <code>Term</code> interface instead.
	 */
	public static final String TABLE_NAME = "CM_Term";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"termId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"modifierId", Types.BIGINT}, {"modifierName", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifierId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifierName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CM_Term (uuid_ VARCHAR(75) null,termId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,modifierId LONG,modifierName VARCHAR(75) null,name VARCHAR(75) null,description STRING null)";

	public static final String TABLE_SQL_DROP = "drop table CM_Term";

	public static final String ORDER_BY_JPQL =
		" ORDER BY term.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CM_Term.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.cm.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.cm.model.Term"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.cm.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.cm.model.Term"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.cm.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.cm.model.Term"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long TERMID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Term toModel(TermSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Term model = new TermImpl();

		model.setUuid(soapModel.getUuid());
		model.setTermId(soapModel.getTermId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifierId(soapModel.getModifierId());
		model.setModifierName(soapModel.getModifierName());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Term> toModels(TermSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Term> models = new ArrayList<Term>(soapModels.length);

		for (TermSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.cm.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.cm.model.Term"));

	public TermModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _termId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTermId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _termId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Term.class;
	}

	@Override
	public String getModelClassName() {
		return Term.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Term)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Term, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Term, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Term)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Term, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Term, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Term>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Term.class.getClassLoader(), Term.class, ModelWrapper.class);

		try {
			Constructor<Term> constructor =
				(Constructor<Term>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Term, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Term, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Term, Object>>();
		Map<String, BiConsumer<Term, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Term, ?>>();

		attributeGetterFunctions.put("uuid", Term::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Term, String>)Term::setUuid);
		attributeGetterFunctions.put("termId", Term::getTermId);
		attributeSetterBiConsumers.put(
			"termId", (BiConsumer<Term, Long>)Term::setTermId);
		attributeGetterFunctions.put("groupId", Term::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Term, Long>)Term::setGroupId);
		attributeGetterFunctions.put("companyId", Term::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Term, Long>)Term::setCompanyId);
		attributeGetterFunctions.put("userId", Term::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Term, Long>)Term::setUserId);
		attributeGetterFunctions.put("userName", Term::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Term, String>)Term::setUserName);
		attributeGetterFunctions.put("createDate", Term::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Term, Date>)Term::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Term::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Term, Date>)Term::setModifiedDate);
		attributeGetterFunctions.put("modifierId", Term::getModifierId);
		attributeSetterBiConsumers.put(
			"modifierId", (BiConsumer<Term, Long>)Term::setModifierId);
		attributeGetterFunctions.put("modifierName", Term::getModifierName);
		attributeSetterBiConsumers.put(
			"modifierName", (BiConsumer<Term, String>)Term::setModifierName);
		attributeGetterFunctions.put("name", Term::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Term, String>)Term::setName);
		attributeGetterFunctions.put("description", Term::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Term, String>)Term::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTermId() {
		return _termId;
	}

	@Override
	public void setTermId(long termId) {
		_columnBitmask |= TERMID_COLUMN_BITMASK;

		if (!_setOriginalTermId) {
			_setOriginalTermId = true;

			_originalTermId = _termId;
		}

		_termId = termId;
	}

	public long getOriginalTermId() {
		return _originalTermId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifierId() {
		return _modifierId;
	}

	@Override
	public void setModifierId(long modifierId) {
		_modifierId = modifierId;
	}

	@JSON
	@Override
	public String getModifierName() {
		if (_modifierName == null) {
			return "";
		}
		else {
			return _modifierName;
		}
	}

	@Override
	public void setModifierName(String modifierName) {
		_modifierName = modifierName;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Term.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Term.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Term toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TermImpl termImpl = new TermImpl();

		termImpl.setUuid(getUuid());
		termImpl.setTermId(getTermId());
		termImpl.setGroupId(getGroupId());
		termImpl.setCompanyId(getCompanyId());
		termImpl.setUserId(getUserId());
		termImpl.setUserName(getUserName());
		termImpl.setCreateDate(getCreateDate());
		termImpl.setModifiedDate(getModifiedDate());
		termImpl.setModifierId(getModifierId());
		termImpl.setModifierName(getModifierName());
		termImpl.setName(getName());
		termImpl.setDescription(getDescription());

		termImpl.resetOriginalValues();

		return termImpl;
	}

	@Override
	public int compareTo(Term term) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(), term.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Term)) {
			return false;
		}

		Term term = (Term)obj;

		long primaryKey = term.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TermModelImpl termModelImpl = this;

		termModelImpl._originalUuid = termModelImpl._uuid;

		termModelImpl._originalTermId = termModelImpl._termId;

		termModelImpl._setOriginalTermId = false;

		termModelImpl._originalGroupId = termModelImpl._groupId;

		termModelImpl._setOriginalGroupId = false;

		termModelImpl._originalCompanyId = termModelImpl._companyId;

		termModelImpl._setOriginalCompanyId = false;

		termModelImpl._setModifiedDate = false;

		termModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Term> toCacheModel() {
		TermCacheModel termCacheModel = new TermCacheModel();

		termCacheModel.uuid = getUuid();

		String uuid = termCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			termCacheModel.uuid = null;
		}

		termCacheModel.termId = getTermId();

		termCacheModel.groupId = getGroupId();

		termCacheModel.companyId = getCompanyId();

		termCacheModel.userId = getUserId();

		termCacheModel.userName = getUserName();

		String userName = termCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			termCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			termCacheModel.createDate = createDate.getTime();
		}
		else {
			termCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			termCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			termCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		termCacheModel.modifierId = getModifierId();

		termCacheModel.modifierName = getModifierName();

		String modifierName = termCacheModel.modifierName;

		if ((modifierName != null) && (modifierName.length() == 0)) {
			termCacheModel.modifierName = null;
		}

		termCacheModel.name = getName();

		String name = termCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			termCacheModel.name = null;
		}

		termCacheModel.description = getDescription();

		String description = termCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			termCacheModel.description = null;
		}

		return termCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Term)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Term)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, Term>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _termId;
	private long _originalTermId;
	private boolean _setOriginalTermId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifierId;
	private String _modifierName;
	private String _name;
	private String _description;
	private long _columnBitmask;
	private Term _escapedModel;

}