/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.cm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Type service. Represents a row in the &quot;CM_Type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.cm.model.impl.TypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.cm.model.impl.TypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Type
 * @generated
 */
@ProviderType
public interface TypeModel
	extends BaseModel<Type>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a type model instance should use the {@link Type} interface instead.
	 */

	/**
	 * Returns the primary key of this type.
	 *
	 * @return the primary key of this type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this type.
	 *
	 * @param primaryKey the primary key of this type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this type.
	 *
	 * @return the uuid of this type
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this type.
	 *
	 * @param uuid the uuid of this type
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the type ID of this type.
	 *
	 * @return the type ID of this type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this type.
	 *
	 * @param typeId the type ID of this type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the group ID of this type.
	 *
	 * @return the group ID of this type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this type.
	 *
	 * @param groupId the group ID of this type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this type.
	 *
	 * @return the company ID of this type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this type.
	 *
	 * @param companyId the company ID of this type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this type.
	 *
	 * @return the user ID of this type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this type.
	 *
	 * @param userId the user ID of this type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this type.
	 *
	 * @return the user uuid of this type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this type.
	 *
	 * @param userUuid the user uuid of this type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this type.
	 *
	 * @return the user name of this type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this type.
	 *
	 * @param userName the user name of this type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this type.
	 *
	 * @return the create date of this type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this type.
	 *
	 * @param createDate the create date of this type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this type.
	 *
	 * @return the modified date of this type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this type.
	 *
	 * @param modifiedDate the modified date of this type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modifier ID of this type.
	 *
	 * @return the modifier ID of this type
	 */
	public long getModifierId();

	/**
	 * Sets the modifier ID of this type.
	 *
	 * @param modifierId the modifier ID of this type
	 */
	public void setModifierId(long modifierId);

	/**
	 * Returns the modifier name of this type.
	 *
	 * @return the modifier name of this type
	 */
	@AutoEscape
	public String getModifierName();

	/**
	 * Sets the modifier name of this type.
	 *
	 * @param modifierName the modifier name of this type
	 */
	public void setModifierName(String modifierName);

	/**
	 * Returns the name of this type.
	 *
	 * @return the name of this type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this type.
	 *
	 * @param name the name of this type
	 */
	public void setName(String name);

	/**
	 * Returns the description of this type.
	 *
	 * @return the description of this type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this type.
	 *
	 * @param description the description of this type
	 */
	public void setDescription(String description);

}